name: Deploy Maven Archetype

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create archetype from project
      run: mvn clean archetype:create-from-project
      
    - name: Update archetype pom.xml for GitHub Packages
      run: |
        cd target/generated-sources/archetype
        # distributionManagement 부분을 GitHub Packages용으로 수정
        sed -i 's|<url>.*</url>|<url>https://maven.pkg.github.com/wizardee/rest-api-archetype</url>|g' pom.xml

    - name: Deploy archetype to GitHub Packages
      run: |
        cd target/generated-sources/archetype
        mvn clean deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
